# Generated by Django 4.1.1 on 2022-10-02 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0002_alter_article_options_article_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='related_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر مربوطه'),
            preserve_default=False,
        ),
    ]
