# Generated by Django 4.1.1 on 2022-10-04 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'کامنت', 'verbose_name_plural': 'کامنت ها'},
        ),
        migrations.AddField(
            model_name='article',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
    ]
