# Generated by Django 4.1.1 on 2022-10-09 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_alter_comment_options_article_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='thumbnail',
            field=models.ImageField(blank=True, default='', upload_to='article-thumbnails'),
        ),
    ]
